#################################################################################################
#
# Site settings
#
# Please visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
#
##################################################################################################
paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge

#*************************************************************************************************
# GENERAL SETTINGS
#*************************************************************************************************
markdown: kramdown
future: true

include: [".well-known"]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Pharo Catalog

description: Pharo Catalog
author:
  name: Pharo Catalog
  email: noreply@pharo.org
  github: pharo-catalog
  twitter: pharoproject
  linkedin: pharoproject
  bio:  Dynamic OO language project.
  email_md5: 42c0cef4d509eedea70a02b9a4276913

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

scholar:
  locale: en
  style: _bibliography/IEEEtran.cls
  bibliography_template: {{reference}}

# set it as url of an image
# sidebar_background_image: ...url

BASE_PATH:

#*************************************************************************************************
# PLUGINS
#*************************************************************************************************
plugins:
  - jekyll-paginate
  - 'jekyll/scholar'
